[package]
name = "easement"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
uuid = { version = "1", features = ["v4"] }
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
hyper-tungstenite = "0.15"
http-body-util = "0.1"
bytes = "1"
futures-util = "0.3"
tokio-tungstenite = "0.24"
chrono = "0.4"
